/*
 * RA Service
 * The RAservice is responsible for handling the request for enrollment and authorization certificates 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.multicert.project.v2x.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Request
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-26T14:56:22.071+01:00")
public class Request {
  @JsonProperty("requestDestination")
  private String requestDestination = null;

  @JsonProperty("requestEncoded")
  private String requestEncoded = null;

  @JsonProperty("requestId")
  private Long requestId = null;

  @JsonProperty("requestOrigin")
  private String requestOrigin = null;

  public Request requestDestination(String requestDestination) {
    this.requestDestination = requestDestination;
    return this;
  }

   /**
   * Get requestDestination
   * @return requestDestination
  **/
  @ApiModelProperty(value = "")
  public String getRequestDestination() {
    return requestDestination;
  }

  public void setRequestDestination(String requestDestination) {
    this.requestDestination = requestDestination;
  }

  public Request requestEncoded(String requestEncoded) {
    this.requestEncoded = requestEncoded;
    return this;
  }

   /**
   * Get requestEncoded
   * @return requestEncoded
  **/
  @ApiModelProperty(value = "")
  public String getRequestEncoded() {
    return requestEncoded;
  }

  public void setRequestEncoded(String requestEncoded) {
    this.requestEncoded = requestEncoded;
  }

  public Request requestId(Long requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @ApiModelProperty(value = "")
  public Long getRequestId() {
    return requestId;
  }

  public void setRequestId(Long requestId) {
    this.requestId = requestId;
  }

  public Request requestOrigin(String requestOrigin) {
    this.requestOrigin = requestOrigin;
    return this;
  }

   /**
   * Get requestOrigin
   * @return requestOrigin
  **/
  @ApiModelProperty(value = "")
  public String getRequestOrigin() {
    return requestOrigin;
  }

  public void setRequestOrigin(String requestOrigin) {
    this.requestOrigin = requestOrigin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Request request = (Request) o;
    return Objects.equals(this.requestDestination, request.requestDestination) &&
        Objects.equals(this.requestEncoded, request.requestEncoded) &&
        Objects.equals(this.requestId, request.requestId) &&
        Objects.equals(this.requestOrigin, request.requestOrigin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestDestination, requestEncoded, requestId, requestOrigin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Request {\n");
    
    sb.append("    requestDestination: ").append(toIndentedString(requestDestination)).append("\n");
    sb.append("    requestEncoded: ").append(toIndentedString(requestEncoded)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    requestOrigin: ").append(toIndentedString(requestOrigin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

