/*
 * RA Service
 * The RAservice is responsible for handling the request for enrollment and authorization certificates 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.multicert.project.v2x.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Response
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-26T14:56:22.071+01:00")
public class Response {
  @JsonProperty("isSuccess")
  private Boolean isSuccess = null;

  @JsonProperty("requestDestination")
  private String requestDestination = null;

  @JsonProperty("requestEncoded")
  private String requestEncoded = null;

  @JsonProperty("requestId")
  private Long requestId = null;

  @JsonProperty("requestOrigin")
  private String requestOrigin = null;

  @JsonProperty("responseDestination")
  private String responseDestination = null;

  @JsonProperty("responseEncoded")
  private String responseEncoded = null;

  @JsonProperty("responseId")
  private Long responseId = null;

  @JsonProperty("responseMessage")
  private String responseMessage = null;

  @JsonProperty("responseOrigin")
  private String responseOrigin = null;

  public Response isSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
    return this;
  }

   /**
   * Get isSuccess
   * @return isSuccess
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsSuccess() {
    return isSuccess;
  }

  public void setIsSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
  }

  public Response requestDestination(String requestDestination) {
    this.requestDestination = requestDestination;
    return this;
  }

   /**
   * Get requestDestination
   * @return requestDestination
  **/
  @ApiModelProperty(value = "")
  public String getRequestDestination() {
    return requestDestination;
  }

  public void setRequestDestination(String requestDestination) {
    this.requestDestination = requestDestination;
  }

  public Response requestEncoded(String requestEncoded) {
    this.requestEncoded = requestEncoded;
    return this;
  }

   /**
   * Get requestEncoded
   * @return requestEncoded
  **/
  @ApiModelProperty(value = "")
  public String getRequestEncoded() {
    return requestEncoded;
  }

  public void setRequestEncoded(String requestEncoded) {
    this.requestEncoded = requestEncoded;
  }

  public Response requestId(Long requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @ApiModelProperty(value = "")
  public Long getRequestId() {
    return requestId;
  }

  public void setRequestId(Long requestId) {
    this.requestId = requestId;
  }

  public Response requestOrigin(String requestOrigin) {
    this.requestOrigin = requestOrigin;
    return this;
  }

   /**
   * Get requestOrigin
   * @return requestOrigin
  **/
  @ApiModelProperty(value = "")
  public String getRequestOrigin() {
    return requestOrigin;
  }

  public void setRequestOrigin(String requestOrigin) {
    this.requestOrigin = requestOrigin;
  }

  public Response responseDestination(String responseDestination) {
    this.responseDestination = responseDestination;
    return this;
  }

   /**
   * Get responseDestination
   * @return responseDestination
  **/
  @ApiModelProperty(value = "")
  public String getResponseDestination() {
    return responseDestination;
  }

  public void setResponseDestination(String responseDestination) {
    this.responseDestination = responseDestination;
  }

  public Response responseEncoded(String responseEncoded) {
    this.responseEncoded = responseEncoded;
    return this;
  }

   /**
   * Get responseEncoded
   * @return responseEncoded
  **/
  @ApiModelProperty(value = "")
  public String getResponseEncoded() {
    return responseEncoded;
  }

  public void setResponseEncoded(String responseEncoded) {
    this.responseEncoded = responseEncoded;
  }

  public Response responseId(Long responseId) {
    this.responseId = responseId;
    return this;
  }

   /**
   * Get responseId
   * @return responseId
  **/
  @ApiModelProperty(value = "")
  public Long getResponseId() {
    return responseId;
  }

  public void setResponseId(Long responseId) {
    this.responseId = responseId;
  }

  public Response responseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
    return this;
  }

   /**
   * Get responseMessage
   * @return responseMessage
  **/
  @ApiModelProperty(value = "")
  public String getResponseMessage() {
    return responseMessage;
  }

  public void setResponseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public Response responseOrigin(String responseOrigin) {
    this.responseOrigin = responseOrigin;
    return this;
  }

   /**
   * Get responseOrigin
   * @return responseOrigin
  **/
  @ApiModelProperty(value = "")
  public String getResponseOrigin() {
    return responseOrigin;
  }

  public void setResponseOrigin(String responseOrigin) {
    this.responseOrigin = responseOrigin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.isSuccess, response.isSuccess) &&
        Objects.equals(this.requestDestination, response.requestDestination) &&
        Objects.equals(this.requestEncoded, response.requestEncoded) &&
        Objects.equals(this.requestId, response.requestId) &&
        Objects.equals(this.requestOrigin, response.requestOrigin) &&
        Objects.equals(this.responseDestination, response.responseDestination) &&
        Objects.equals(this.responseEncoded, response.responseEncoded) &&
        Objects.equals(this.responseId, response.responseId) &&
        Objects.equals(this.responseMessage, response.responseMessage) &&
        Objects.equals(this.responseOrigin, response.responseOrigin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isSuccess, requestDestination, requestEncoded, requestId, requestOrigin, responseDestination, responseEncoded, responseId, responseMessage, responseOrigin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    isSuccess: ").append(toIndentedString(isSuccess)).append("\n");
    sb.append("    requestDestination: ").append(toIndentedString(requestDestination)).append("\n");
    sb.append("    requestEncoded: ").append(toIndentedString(requestEncoded)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    requestOrigin: ").append(toIndentedString(requestOrigin)).append("\n");
    sb.append("    responseDestination: ").append(toIndentedString(responseDestination)).append("\n");
    sb.append("    responseEncoded: ").append(toIndentedString(responseEncoded)).append("\n");
    sb.append("    responseId: ").append(toIndentedString(responseId)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    responseOrigin: ").append(toIndentedString(responseOrigin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

