/*
 * RA Service
 * The RAservice is responsible for handling the request for enrollment and authorization certificates 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.multicert.project.v2x.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ConfigResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-26T14:56:22.071+01:00")
public class ConfigResponse {
  @JsonProperty("aaCert")
  private String aaCert = null;

  @JsonProperty("eaCert")
  private String eaCert = null;

  @JsonProperty("isSuccess")
  private Boolean isSuccess = null;

  @JsonProperty("responseDestination")
  private String responseDestination = null;

  @JsonProperty("responseId")
  private Long responseId = null;

  @JsonProperty("responseMessage")
  private String responseMessage = null;

  @JsonProperty("responseOrigin")
  private String responseOrigin = null;

  @JsonProperty("trustAnchor")
  private String trustAnchor = null;

  @JsonProperty("trustedAA")
  private String trustedAA = null;

  public ConfigResponse aaCert(String aaCert) {
    this.aaCert = aaCert;
    return this;
  }

   /**
   * Get aaCert
   * @return aaCert
  **/
  @ApiModelProperty(value = "")
  public String getAaCert() {
    return aaCert;
  }

  public void setAaCert(String aaCert) {
    this.aaCert = aaCert;
  }

  public ConfigResponse eaCert(String eaCert) {
    this.eaCert = eaCert;
    return this;
  }

   /**
   * Get eaCert
   * @return eaCert
  **/
  @ApiModelProperty(value = "")
  public String getEaCert() {
    return eaCert;
  }

  public void setEaCert(String eaCert) {
    this.eaCert = eaCert;
  }

  public ConfigResponse isSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
    return this;
  }

   /**
   * Get isSuccess
   * @return isSuccess
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsSuccess() {
    return isSuccess;
  }

  public void setIsSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
  }

  public ConfigResponse responseDestination(String responseDestination) {
    this.responseDestination = responseDestination;
    return this;
  }

   /**
   * Get responseDestination
   * @return responseDestination
  **/
  @ApiModelProperty(value = "")
  public String getResponseDestination() {
    return responseDestination;
  }

  public void setResponseDestination(String responseDestination) {
    this.responseDestination = responseDestination;
  }

  public ConfigResponse responseId(Long responseId) {
    this.responseId = responseId;
    return this;
  }

   /**
   * Get responseId
   * @return responseId
  **/
  @ApiModelProperty(value = "")
  public Long getResponseId() {
    return responseId;
  }

  public void setResponseId(Long responseId) {
    this.responseId = responseId;
  }

  public ConfigResponse responseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
    return this;
  }

   /**
   * Get responseMessage
   * @return responseMessage
  **/
  @ApiModelProperty(value = "")
  public String getResponseMessage() {
    return responseMessage;
  }

  public void setResponseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
  }

  public ConfigResponse responseOrigin(String responseOrigin) {
    this.responseOrigin = responseOrigin;
    return this;
  }

   /**
   * Get responseOrigin
   * @return responseOrigin
  **/
  @ApiModelProperty(value = "")
  public String getResponseOrigin() {
    return responseOrigin;
  }

  public void setResponseOrigin(String responseOrigin) {
    this.responseOrigin = responseOrigin;
  }

  public ConfigResponse trustAnchor(String trustAnchor) {
    this.trustAnchor = trustAnchor;
    return this;
  }

   /**
   * Get trustAnchor
   * @return trustAnchor
  **/
  @ApiModelProperty(value = "")
  public String getTrustAnchor() {
    return trustAnchor;
  }

  public void setTrustAnchor(String trustAnchor) {
    this.trustAnchor = trustAnchor;
  }

  public ConfigResponse trustedAA(String trustedAA) {
    this.trustedAA = trustedAA;
    return this;
  }

   /**
   * Get trustedAA
   * @return trustedAA
  **/
  @ApiModelProperty(value = "")
  public String getTrustedAA() {
    return trustedAA;
  }

  public void setTrustedAA(String trustedAA) {
    this.trustedAA = trustedAA;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigResponse configResponse = (ConfigResponse) o;
    return Objects.equals(this.aaCert, configResponse.aaCert) &&
        Objects.equals(this.eaCert, configResponse.eaCert) &&
        Objects.equals(this.isSuccess, configResponse.isSuccess) &&
        Objects.equals(this.responseDestination, configResponse.responseDestination) &&
        Objects.equals(this.responseId, configResponse.responseId) &&
        Objects.equals(this.responseMessage, configResponse.responseMessage) &&
        Objects.equals(this.responseOrigin, configResponse.responseOrigin) &&
        Objects.equals(this.trustAnchor, configResponse.trustAnchor) &&
        Objects.equals(this.trustedAA, configResponse.trustedAA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aaCert, eaCert, isSuccess, responseDestination, responseId, responseMessage, responseOrigin, trustAnchor, trustedAA);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigResponse {\n");
    
    sb.append("    aaCert: ").append(toIndentedString(aaCert)).append("\n");
    sb.append("    eaCert: ").append(toIndentedString(eaCert)).append("\n");
    sb.append("    isSuccess: ").append(toIndentedString(isSuccess)).append("\n");
    sb.append("    responseDestination: ").append(toIndentedString(responseDestination)).append("\n");
    sb.append("    responseId: ").append(toIndentedString(responseId)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("    responseOrigin: ").append(toIndentedString(responseOrigin)).append("\n");
    sb.append("    trustAnchor: ").append(toIndentedString(trustAnchor)).append("\n");
    sb.append("    trustedAA: ").append(toIndentedString(trustedAA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

